base/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from base import settings

urlpatterns = [

    path('', include('blog.urls')),
    path("account/", include('account.urls')),
    path("admin/", admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('list/<slug:slug>/', views.list, name='list'),
    path('catalog/', views.catalog, name='catalog'),
    path('details/<slug:slug>/', views.details, name='details'),
    path('moviedetails/<slug:slug>/', views.moviedetails, name='moviedetails'),
    path('castdetails/<slug:slug>/', views.castdetails, name='castdetails'),
]

blog/models.py
import string
from random import random

from django.db import models
from django.core.validators import MinLengthValidator
from django.utils.text import slugify
from colorfield.fields import ColorField


# Create your models here.



class movie_type(models.Model):
    type = models.CharField(max_length=100)

    def __str__(self):
        return self.type

choices = (
    ('News', 'News'),
    ('Sport', 'Sport'),
    ('Travel', 'Travel'),
    ('Technology', 'Technology'),
)
class bloger_type(models.Model):
    type = models.CharField(choices=choices,max_length=100)

    def __str__(self):#admin panelinde isimleri ile listelenmelerini sağlıyor
        return self.type


class movie_cast(models.Model):

    genders = (
        ('M', 'Erkek'),
        ('F', 'Kadın'),
    )

    duty_types = (
        ('1','Görevli'),
        ('2', 'Oyuncu'),
        ('3', 'Yönetmen'),
        ('4', 'Senarist'),
    )

    first_name = models.CharField(max_length=50, verbose_name='İsim')
    last_name = models.CharField(max_length=50, verbose_name='Soyisim')
    biography = models.TextField(validators= [MinLengthValidator(20)], verbose_name='Biyografi')
    image = models.FileField(upload_to="images", verbose_name='Kişi Fotoğrafı')
    date_of_birth = models.DateField(verbose_name='Doğum Tarihi')
    gender = models.CharField(max_length=1, choices=genders, verbose_name='Cinsiyet')
    duty_type = models.CharField(max_length=1, choices=duty_types, verbose_name='İş Pozisyonu')
    nationality = models.CharField(max_length=50, verbose_name='Uyruk')
    castslug = models.SlugField(unique=True, verbose_name='Kişi Slug')

    class Meta:
        verbose_name = "Kast Ekibi"
        verbose_name_plural = "Kast Ekibi"

    #def save(self, *args, **kwargs):
        #self.castslug = slugify(self.first_name)
        #super().save(args, kwargs)

    @property #oyuncunun admin panelinde isminin gözükmesi icin admin.py list_display ile birlikte calısıyo
    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    full_name.fget.short_description = "isim soyisim"

    def __str__(self): #bak
        return f"{self.first_name} {self.last_name} ({self.duty_types[int(self.duty_type)-1][1]})"


class Movie(models.Model):
    movie_title = models.CharField(max_length=100, verbose_name="Film İsmi")
    movie_description = models.TextField(validators= [MinLengthValidator(20)], verbose_name='Film Açıklaması')
    mark = models.DecimalField(max_digits=2, decimal_places=1, verbose_name="Film Puanı")
    movie_pic = models.FileField(upload_to="images", verbose_name='Film Fotoğrafı')
    movie_date = models.DateField(auto_now = True, verbose_name="Film İncelemesi Oluşturma Tarihi")
    movie_slug = models.SlugField(unique=True, verbose_name='Film Slug')
    movie_budget = models.DecimalField(max_digits=20, decimal_places=0, verbose_name="Film Bütçesi")
    cast_people = models.ManyToManyField(movie_cast, related_name='movie_cast', verbose_name="Film Kadrosu")
    movie_types = models.ManyToManyField(movie_type, verbose_name='Film Tipi')

    class Meta:
        verbose_name = "Film İncelemesi"
        verbose_name_plural = "Film İncelemeleri"
    #def save(self, *args, **kwargs):
        #self.movie_slug = slugify(self.movie_title)
        #super().save(args, kwargs)

    def __str__(self):
        return self.movie_title

class Bloger(models.Model):
    bloger_title = models.CharField(max_length=100, verbose_name="Blog Yazısı Başlığı")
    bloger_description = models.TextField(validators= [MinLengthValidator(20)], verbose_name='Blog Yazısı')
    bloger_pic = models.FileField(upload_to="images", verbose_name='Blog Yazısı Fotoğrafı')
    bloger_date = models.DateField(auto_now = True, verbose_name="Blog Yazısı Oluşturma Tarihi")
    bloger_slug = models.SlugField(unique=True, verbose_name='Blog Yazısı Slug')
    bloger_types = models.ManyToManyField(bloger_type, verbose_name='Blog Yazısı Tipi')

    class Meta:
        verbose_name = "Blog Yazısı"
        verbose_name_plural = "Blog Yazıları"

    # def save(self, *args, **kwargs):
    #     self.bloger_slug = slugify(self.bloger_title)
    #     super().save(args, kwargs)
    def __str__(self):
        return self.bloger_title

class movie_video(models.Model):
    title = models.CharField(max_length=100)
    url = models.CharField(max_length=200)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class bloger_video(models.Model):
    title = models.CharField(max_length=100)
    url = models.CharField(max_length=200)
    bloger = models.ForeignKey(Bloger, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class WebsiteSettings(models.Model):
    settingname = models.CharField(max_length=40, null=True, verbose_name="Site Ayarı İsmi", help_text="Site Ayarı ismini giriniz")
    navbarcolor = ColorField(default="#0D50B0",verbose_name="Menü Rengi",help_text="Menü rengini giriniz.")
    navbarlogo = models.CharField(max_length=250,verbose_name="Menü Logosu",help_text="Menü logosunu giriniz.")
    backgroundcolor =  ColorField(default="#EEF1F4",verbose_name="Arka Plan Rengi",help_text="Site için arka plan rengi giriniz.")
    aboutustext = models.TextField(max_length=500,verbose_name="Hakkımızda Bilgisi",help_text="Hakkımızda kısmını doldurunuz.")
    contactphone = models.CharField(max_length=250,verbose_name="İletişim Numarası",help_text="İletişim numarası giriniz.")
    contactmail = models.CharField(max_length=250,verbose_name="İletişim Maili",help_text="İletişim maili giriniz.")
    contactadres = models.TextField(max_length=250,verbose_name="İletişim Adres",help_text="İletişim adresi giriniz.")
    footer = models.CharField(max_length=250,verbose_name="Footer Metni",help_text="Footer metni giriniz.")
    footercolor = ColorField(default="#d6d9e3",verbose_name="Footer Rengi",help_text="Footer rengini giriniz.")
    bottomfootercolor = ColorField(default="#0D50B0",verbose_name="Alt Footer Rengi",help_text="Alt Footer rengini giriniz.")
    twitter = models.CharField(max_length=250,verbose_name="Twitter URL Bağlantısı",help_text="Twitter adresinizi giriniz.")
    facebook = models.CharField(max_length=250,verbose_name="Facebook URL Bağlantısı",help_text="Facebook adresinizi giriniz.")
    instagram = models.CharField(max_length=250,verbose_name="Instagram URL Bağlantısı",help_text="Instagram adresinizi giriniz.")

    class Meta:
        verbose_name = "Web Sitesi Ayarı"
        verbose_name_plural = "Web Sitesi Ayarları"

    def __str__(self):
        return self.settingname


class Product(models.Model):
    product_title = models.CharField(max_length=30, null=True, blank=True)

class ImagesGal(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, null=True, blank=True)
    image = models.ImageField(upload_to="images", null=True, blank=True, )

    def __str__(self):
        return self.title or "Unnamed Image"

blog/forms.py
from django import forms
from blog.models import Product, ImagesGal

class ProductForm(forms.ModelForm):
    image_files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = Product
        fields = ['product_title']

blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from blog.models import Movie, Bloger, movie_cast, Product
import random



def index(request):
    sliders = Product.objects.all()
    news = Bloger.objects.filter(bloger_types__type="News")
    sport = Bloger.objects.filter(bloger_types__type="Sport")
    travel = Bloger.objects.filter(bloger_types__type="Travel")
    technology = Bloger.objects.filter(bloger_types__type="Technology")
    movie = Movie.objects.all()

    #all_news = list(Bloger.objects.filter(bloger_types__type="News"))
    recent_new = news.order_by('-id')[:3]
    recent_sport = sport.order_by('-id')[:1:-1]
    recent_travel = travel.order_by('-id')[:1:-1]
    recent_technology = technology.order_by('-id')[:1:-1]
    recent_movie = movie.order_by('-id')[:6:-1]


    #number_of_news = news.count()
    #news_random = random.randint(0, number_of_news-1)


    # number_of_news = news.count()
    # random_new = random.sample(news, number_of_news)
    #
    # all_sport = list(Bloger.objects.filter(bloger_types__type="Sport"))
    # number_of_sport = sport.count()
    # random_sport = random.sample(all_sport, number_of_sport)
    #
    # all_travel = list(Bloger.objects.filter(bloger_types__type="Travel"))
    # number_of_travel = travel.count()
    # random_travel = random.sample(all_travel, number_of_travel)
    #
    # all_technology = list(Bloger.objects.filter(bloger_types__type="Technology"))
    # number_of_technology = technology.count()
    # random_technology = random.sample(all_technology, number_of_technology)
    #
    # all_movie = list(Movie.objects.all())
    # number_of_movie = movie.count()
    # random_movie = random.sample(all_movie, number_of_movie)



    context = {
        "news": news,
        "sport": sport,
        "travel": travel,
        "technology": technology,
        "movie": movie,
        "recent_new": recent_new,
        "recent_sport": recent_sport,
        "recent_travel": recent_travel,
        "recent_technology": recent_technology,
        "recent_movie": recent_movie,
        "sliders": sliders
        #"random_new": random_new,
        # "random_sport": random_sport,
        # "random_travel": random_travel,
        # "random_technology": random_technology,
        # "random_movie": random_movie
    }
    return render(request, 'blog/index.html', context)


def list(request, slug):
    if slug == 'news':
        news = Bloger.objects.filter(bloger_types__type="News").order_by('-id')
        context = {
            "news": news
        }
        return render(request, 'blog/list.html', context)

    elif slug == 'sport':
        sport = Bloger.objects.filter(bloger_types__type="Sport").order_by('-id')
        context = {
            "sport": sport
        }
        return render(request, 'blog/list.html', context)

    elif slug == 'travel':
        travel = Bloger.objects.filter(bloger_types__type="Travel").order_by('-id')
        context = {
            "travel": travel
        }
        return render(request, 'blog/list.html', context)

    elif slug == 'technology':
        technology = Bloger.objects.filter(bloger_types__type="Technology").order_by('-id')
        context = {
            "technology": technology
        }
        return render(request, 'blog/list.html', context)

    elif slug == 'movie':
        movie = Movie.objects.all().order_by('-id')
        context = {
            "movie": movie
        }
        return render(request, 'blog/list.html', context)


def details(request, slug):
    blog = Bloger.objects.get(bloger_slug=slug)
    context = {
        "blog": blog
    }
    return render(request, 'blog/details.html', context)



def moviedetails(request, slug):
    movie = Movie.objects.get(movie_slug=slug)
    #moviecast = Movie.objects.filter(cast_people__in=)
    #moviecast = Movie.objects.filter(cast_people__in=value)
    #moviecast = movie_cast.objects.filter(movie__cast_people=)
    #moviecast = movie_cast.objects.all()
    context = {
        "movie": movie,
        #"movie_cast": moviecast
    }
    return render(request, 'blog/moviedetails.html', context)


@login_required(login_url="/account/login")
def castdetails(request, slug):
    moviecast = movie_cast.objects.get(castslug=slug)
    context = {
        "moviecast": moviecast,
    }
    return render(request, 'blog/castdetails.html', context)


def catalog(request):
    if request.method == 'GET':
        q = request.GET['q']
        if q and q is not None:
            product = Bloger.objects.filter(bloger_title__contains=q)
            product2 = Movie.objects.filter(movie_title__contains=q)


        else:
            return HttpResponse

        context = {
            "products": product,
            "products2": product2,
        }

        return render(request, 'blog/catalog.html', context)

blog/templates/blog/castdetails.html
{% extends 'base.html' %}

{% load static %}


{% block css_files %}
{% endblock %}


{% block page_tittle %}
    Cast Details
{% endblock %}


{% block content %}


    <div class="container bubble">
        <div class="row">
            <div class="col mobile-mt">

                <div class="card mb-3 mt-4">
                    <h5 class="card-title text-center mt-3 ml-2 fw-bold display-4">{{ moviecast.first_name }} {{ moviecast.last_name }}</h5>
                    <div class="row">
                        <div class="col-8">
                            <img class="card-img-top mt-3 ml-3" src="{{ moviecast.image.url }}" alt="Card image cap"
                                 height="500">
                        </div>
                        <div class="col-4 m-auto">

                            <p class="card-text font-weight-bold details mt-5">Birth Date: <span class="insidedetails">{{ moviecast.date_of_birth }}</span></p>


                            <p class="card-text font-weight-bold details mt-5">Nationality: <span class="insidedetails">{{ moviecast.nationality }}</span></p>



                            {% if moviecast.gender == "M" %}
                                <p class="card-text font-weight-bold details mt-5">Gender: <span class="insidedetails">Male</span></p>
                            {% endif %}
                            {% if moviecast.nationality == "F" %}
                                <p class="card-text font-weight-bold details mt-5">Gender: <span class="insidedetails">Female</span></p>
                            {% endif %}


                            {% if moviecast.duty_type == "1" %}
                                <p class="card-text font-weight-bold details mt-5">Duty: <span class="insidedetails">Görevli</span></p>
                            {% endif %}
                            {% if moviecast.duty_type == "2" %}
                                <p class="card-text font-weight-bold details mt-5">Duty: <span class="insidedetails">Oyuncu</span></p>
                            {% endif %}
                            {% if moviecast.duty_type == "3" %}
                                <p class="card-text font-weight-bold details mt-5">Duty: <span class="insidedetails">Yönetmen</span></p>
                            {% endif %}
                            {% if moviecast.duty_type == "4" %}
                                <p class="card-text font-weight-bold details mt-5">Duty: <span class="insidedetails">Senarist</span></p>
                            {% endif %}


                        </div>
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ moviecast.biography }}</p>

                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

blog/templates/blog/catalog.html
{% extends 'base.html' %}

{% load static %}

{% block css_files %}

    <link rel="stylesheet" type="text/css" href="{% static 'vendor/slick/slick.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/slick/slick-theme.min.css' %}"/>

{% endblock %}


{% block page_tittle %}

    Catalog

{% endblock %}

{% block content %}

    <div class="container freepage">
        <div class="row">
            <div class="col mobile-mt">


                {% for product in products2 %}
                    <a class="linkler" href="/moviedetails/{{ product.movie_slug }}" >
                        <div class="card mb-3 mt-3" >
                            <div class="card-body " >
                                <div class="row no-gutters">
                                    <div class="col-md-3">
                                        <img src="{{ product.movie_pic.url }}" class="card-img" alt="..." height="200">
                                    </div>
                                    <div class="col-md-9">
                                        <div class="card-body">
                                            <h5 class="card-title"> <h1>{{ product.movie_title }}</h1></h5>
                                            <p class="card-text">{{ product.movie_description|truncatechars:150 }} </p>
                                            <p class="card-text"><small class="text-muted">{{ item.movie_date }}</small></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endfor %}

                {% for product in products %}
                    <a class="linkler" href="/details/{{ product.bloger_slug }}" >
                        <div class="card mb-3 mt-3" >
                            <div class="card-body " >
                                <div class="row no-gutters">
                                    <div class="col-md-3">
                                        <img src="{{ product.bloger_pic.url }}" class="card-img" alt="..." height="200">
                                    </div>
                                    <div class="col-md-9">
                                        <div class="card-body">
                                            <h5 class="card-title"> <h1>{{ product.bloger_title }}</h1></h5>
                                            <p class="card-text">{{ product.bloger_description|truncatechars:150 }} </p>
                                            <p class="card-text"><small class="text-muted">{{ item.bloger_date }}</small></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                {% endfor %}





            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/details.html
{% extends 'base.html' %}

{% load static %}


{% block css_files %}
{% endblock %}


{% block page_tittle %}
    Details
{% endblock %}


{% block content %}


    <div class="container bubble">
        <div class="row">
            <div class="col mobile-mt">

                <div class="card mb-3 mt-4">
                    <h5 class="card-title text-center mt-3 ml-2 fw-bold display-4">{{ blog.bloger_title }}</h5>
                    <img class="card-img-top mt-3" src="{{ blog.bloger_pic.url }}" alt="Card image cap" height="450">
                    <div class="card-body">
                        <p class="card-text">{{ blog.bloger_description }}</p>
                        <p class="card-text"><small class="text-muted">{{ blog.bloger_date }}</small></p>
                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% load static %}

{% block css_files %}



{% endblock %}


{% block page_tittle %}
    Home
{% endblock %}


{% block content %}
    <div class="container bubble ">

        <div class="row no-gutters">
            <div class="col mobile-mt">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for slider in sliders %}
                            {% for photo in slider.imagesgal_set.all %}
                                <li data-target="#carouselExampleIndicators"
                                    data-slide-to="{{ forloop.parentloop.counter0 }}{{ forloop.counter0 }}"
                                    {% if forloop.parentloop.first and forloop.first %}class="active"{% endif %}></li>
                            {% endfor %}
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for slider in sliders %}
                            {% for photo in slider.imagesgal_set.all %}
                                <div class="carousel-item {% if forloop.parentloop.first and forloop.first %} active {% endif %}"
                                     id="slide{{ forloop.parentloop.counter }}{{ forloop.counter }}">
                                    <img class="d-block w-100 mainfotoindex" src="{{ photo.image.url }}"
                                         alt="{{ photo.title }}" height="400">
                                </div>
                            {% endfor %}
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>


        {#        <div class=" row no-gutters ">#}
        {#            <div class="col mobile-mt">#}
        {#                <div id="carouselExampleIndicators" class="carousel slide " data-ride="carousel">#}
        {#                    <ol class="carousel-indicators">#}
        {#                        {% for galery_photo in slider_photos %}#}
        {#                            {% for galery_image in galery_photo.galeryimage_set.all %}#}
        {#                                <li data-target="#carouselExampleIndicators"#}
        {#                                    data-slide-to="{{ forloop.parentloop.counter0 }}"#}
        {#                                        {% if forloop.parentloop.first and forloop.first %}#}
        {#                                    class="active" {% endif %}></li>#}
        {#                            {% endfor %}#}
        {#                        {% endfor %}#}
        {#                    </ol>#}
        {#                    <div class="carousel-inner ">#}
        {#                        {% for galery_photo in slider_photos %}#}
        {#                            {% for galery_image in galery_photo.galeryimage_set.all %}#}
        {#                                <div class="carousel-item {% if forloop.parentloop.first and forloop.first %} active {% endif %}"#}
        {#                                     id="slide{{ forloop.parentloop.counter0 }}">#}
        {##}
        {#                                    <img class="d-block w-100 heigtimg" src="{{ galery_image.galery_pic.url }}"#}
        {#                                         alt="First slide">#}
        {##}
        {#                                </div>#}
        {#                            {% endfor %}#}
        {#                        {% endfor %}#}
        {#                    </div>#}
        {#                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"#}
        {#                       data-slide="prev">#}
        {#                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>#}
        {#                        <span class="sr-only">Previous</span>#}
        {#                    </a>#}
        {#                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"#}
        {#                       data-slide="next">#}
        {#                        <span class="carousel-control-next-icon" aria-hidden="true"></span>#}
        {#                        <span class="sr-only">Next</span>#}
        {#                    </a>#}
        {#                </div>#}
        {#            </div>#}
        {#        </div>#}


        <div class="row">
            <div class="col mobile-mt">
                <h1 class="mt-3 ml-2 fw-bold display-4">News</h1>

                <div id="carouselExampleIndicators" class="carousel slide mt-3" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        {% for x in recent_new %}
                            <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %} "
                                 id="slide{{ forloop.counter }}">

                                <a href="details/{{ x.bloger_slug }}"><img class="d-block w-100"
                                                                           src="{{ x.bloger_pic.url }}"
                                                                           alt="First slide" height="450">

                                    <div class="carousel-caption d-none d-md-block mb-4 " style="">
                                        <div class="bg-dark "
                                             style="opacity: 0.9; position: absolute; z-index: 1; top: 0; left: 0; width:100%; height: 30px"></div>
                                        <div class="text-center "
                                             style=" position: absolute; z-index: 2; top: 2px; left: 0; width:100%; height: 20px">
                                            <h5>{{ x.bloger_title }}</h5>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <h1 class="mt-3 ml-2 fw-bold display-4">Trends</h1>
                <div class="card-deck mt-3">
                    <div class="card">
                        <a href="details/{{ recent_travel.0.bloger_slug }}" class="linkler">
                            <img class="card-img-top" src="{{ recent_travel.0.bloger_pic.url }}" alt="Card image cap"
                                 height="300">
                            <div class="card-body">
                                <h5 class="card-title">{{ recent_travel.0.bloger_title }}</h5>
                                <p class="card-text">{{ recent_travel.0.bloger_description|truncatechars:80 }}</p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">{{ recent_travel.0.bloger_date }}</small>
                            </div>
                        </a>
                    </div>
                    <div class="card">
                        <a href="details/{{ recent_sport.0.bloger_slug }}" class="linkler">
                            <img class="card-img-top" src="{{ recent_sport.0.bloger_pic.url }}" alt="Card image cap"
                                 height="300">
                            <div class="card-body">
                                <h5 class="card-title">{{ recent_sport.0.bloger_title }}</h5>
                                <p class="card-text">{{ recent_sport.0.bloger_description|truncatechars:80 }}</p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">{{ recent_sport.0.bloger_date }}</small>
                            </div>
                        </a>
                    </div>
                    <div class="card">
                        <a href="details/{{ recent_technology.0.bloger_slug }}" class="linkler">
                            <img class="card-img-top" src="{{ recent_technology.0.bloger_pic.url }}"
                                 alt="Card image cap"
                                 height="300">
                            <div class="card-body">
                                <h5 class="card-title">{{ recent_technology.0.bloger_title }}</h5>
                                <p class="card-text">{{ recent_technology.0.bloger_description|truncatechars:80 }}</p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">{{ recent_technology.0.bloger_date }}</small>
                            </div>
                        </a>
                    </div>
                </div>

                <h1 class="mt-3 ml-2 fw-bold display-4">Movies</h1>
                <div class="owl-carousel owl-theme mt-3">
                    {% for x in recent_movie %}
                        <div class="item">
                            <a href="moviedetails/{{ x.movie_slug }}">
                                <div class="card">
                                    <img src="{{ x.movie_pic.url }}" height="350">
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}